import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import styles from "../styles/Home.module.scss";
import Yellowbar from "../components/Yellowbar";
import FourSteps from "../components/steps/index";
import "../fontawesome";

const Home: NextPage = () => {
  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <Yellowbar />
      <FourSteps />
    </div>
  );
};

export default Home;
